const moviesData = [
    { title: "The Shawshank Redemption", description: "Two imprisoned men bond over years.", rating: 9.3, releaseDate: new Date("1994-10-14"), duration: 142 },
    { title: "The Godfather", description: "A mafia family saga.", rating: 9.2, releaseDate: new Date("1972-03-24"), duration: 175 },
    { title: "Pulp Fiction", description: "Interwoven crime stories.", rating: 8.9, releaseDate: new Date("1994-10-14"), duration: 154 },
    { title: "Inception", description: "A thief enters dreams.", rating: 8.8, releaseDate: new Date("2010-07-16"), duration: 148 },
    { title: "The Dark Knight", description: "Batman faces the Joker.", rating: 9.0, releaseDate: new Date("2008-07-18"), duration: 152 },
    { title: "Forrest Gump", description: "A man’s extraordinary life.", rating: 8.8, releaseDate: new Date("1994-07-06"), duration: 142 },
    { title: "The Matrix", description: "A hacker discovers reality.", rating: 8.7, releaseDate: new Date("1999-03-31"), duration: 136 },
    { title: "Titanic", description: "A tragic love story aboard a ship.", rating: 7.8, releaseDate: new Date("1997-12-19"), duration: 195 },
    { title: "Schindler's List", description: "A man saves Jews in WWII.", rating: 8.9, releaseDate: new Date("1993-12-15"), duration: 195 },
    { title: "Fight Club", description: "An underground fight club forms.", rating: 8.8, releaseDate: new Date("1999-10-15"), duration: 139 },
    { title: "The Empire Strikes Back", description: "Rebels fight an empire.", rating: 8.7, releaseDate: new Date("1980-05-21"), duration: 124 },
    { title: "The Lord of the Rings: The Fellowship of the Ring", description: "A quest begins.", rating: 8.8, releaseDate: new Date("2001-12-19"), duration: 178 },
    { title: "Gladiator", description: "A general seeks revenge.", rating: 8.5, releaseDate: new Date("2000-05-05"), duration: 155 },
    { title: "The Silence of the Lambs", description: "A killer helps the FBI.", rating: 8.6, releaseDate: new Date("1991-02-14"), duration: 118 },
    { title: "Saving Private Ryan", description: "A WWII rescue mission.", rating: 8.6, releaseDate: new Date("1998-07-24"), duration: 169 },
    { title: "Jurassic Park", description: "Dinosaurs escape a park.", rating: 8.1, releaseDate: new Date("1993-06-11"), duration: 127 },
    { title: "The Lion King", description: "A prince reclaims his throne.", rating: 8.5, releaseDate: new Date("1994-06-15"), duration: 88 },
    { title: "Back to the Future", description: "Time travel adventure.", rating: 8.5, releaseDate: new Date("1985-07-03"), duration: 116 },
    { title: "The Avengers", description: "Heroes unite to save Earth.", rating: 8.0, releaseDate: new Date("2012-05-04"), duration: 143 },
    { title: "Interstellar", description: "A journey beyond Earth.", rating: 8.6, releaseDate: new Date("2014-11-07"), duration: 169 },
    { title: "The Departed", description: "Cops and criminals collide.", rating: 8.5, releaseDate: new Date("2006-10-06"), duration: 151 },
    { title: "Good Will Hunting", description: "A genius finds his path.", rating: 8.3, releaseDate: new Date("1997-12-05"), duration: 126 },
    { title: "The Green Mile", description: "A prisoner has a gift.", rating: 8.6, releaseDate: new Date("1999-12-10"), duration: 189 },
    { title: "Avatar", description: "A marine on an alien planet.", rating: 7.8, releaseDate: new Date("2009-12-18"), duration: 162 },
    { title: "Mad Max: Fury Road", description: "A wild desert chase.", rating: 8.1, releaseDate: new Date("2015-05-15"), duration: 120 },
    { title: "The Wolf of Wall Street", description: "A broker’s wild life.", rating: 8.2, releaseDate: new Date("2013-12-25"), duration: 180 },
    { title: "Parasite", description: "A family infiltrates another.", rating: 8.6, releaseDate: new Date("2019-05-30"), duration: 132 },
    { title: "The Prestige", description: "Magicians rivalry turns dark.", rating: 8.5, releaseDate: new Date("2006-10-20"), duration: 130 },
    { title: "Django Unchained", description: "A slave seeks freedom.", rating: 8.4, releaseDate: new Date("2012-12-25"), duration: 165 },
    { title: "Whiplash", description: "A drummer’s intense mentor.", rating: 8.5, releaseDate: new Date("2014-10-10"), duration: 106 },
    { title: "The Grand Budapest Hotel", description: "A quirky hotel tale.", rating: 8.1, releaseDate: new Date("2014-03-07"), duration: 99 },
    { title: "La La Land", description: "Dreams clash with love.", rating: 8.0, releaseDate: new Date("2016-12-09"), duration: 128 },
    { title: "The Social Network", description: "Facebook’s origin story.", rating: 7.7, releaseDate: new Date("2010-10-01"), duration: 120 },
    { title: "Blade Runner 2049", description: "A future mystery unfolds.", rating: 8.0, releaseDate: new Date("2017-10-06"), duration: 164 },
    { title: "The Incredibles", description: "A superhero family returns.", rating: 8.0, releaseDate: new Date("2004-11-05"), duration: 115 },
    { title: "Toy Story", description: "Toys come to life.", rating: 8.3, releaseDate: new Date("1995-11-22"), duration: 81 },
    { title: "The Shining", description: "A writer descends into madness.", rating: 8.4, releaseDate: new Date("1980-05-23"), duration: 146 },
    { title: "A Clockwork Orange", description: "A dystopian crime tale.", rating: 8.3, releaseDate: new Date("1971-12-19"), duration: 136 },
    { title: "The Big Lebowski", description: "A slacker gets in trouble.", rating: 8.1, releaseDate: new Date("1998-03-06"), duration: 117 },
    { title: "No Country for Old Men", description: "A hunter finds trouble.", rating: 8.1, releaseDate: new Date("2007-11-09"), duration: 122 },
    { title: "Se7en", description: "Detectives hunt a killer.", rating: 8.6, releaseDate: new Date("1995-09-22"), duration: 127 },
    { title: "Braveheart", description: "A warrior fights for freedom.", rating: 8.3, releaseDate: new Date("1995-05-24"), duration: 178 },
    { title: "The Truman Show", description: "A man’s life is a TV show.", rating: 8.1, releaseDate: new Date("1998-06-05"), duration: 103 },
    { title: "Eternal Sunshine of the Spotless Mind", description: "Love erased from memory.", rating: 8.3, releaseDate: new Date("2004-03-19"), duration: 108 },
    { title: "Catch Me If You Can", description: "A con man’s tale.", rating: 8.1, releaseDate: new Date("2002-12-25"), duration: 141 },
    { title: "The Sixth Sense", description: "A boy sees dead people.", rating: 8.1, releaseDate: new Date("1999-08-06"), duration: 107 },
    { title: "Memento", description: "A man with no memory solves a crime.", rating: 8.4, releaseDate: new Date("2000-10-11"), duration: 113 },
    { title: "The Usual Suspects", description: "A twisty crime story.", rating: 8.5, releaseDate: new Date("1995-08-16"), duration: 106 },
    { title: "Spirited Away", description: "A girl in a spirit world.", rating: 8.6, releaseDate: new Date("2001-07-20"), duration: 125 },
    { title: "Coco", description: "A boy uncovers family secrets.", rating: 8.4, releaseDate: new Date("2017-11-22"), duration: 105 },
  ];
  module.exports=moviesData